spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/condo_swift_db
    username: postgres
    password: 257890
    
#  flyway:
#    enabled: true
#    locations: classpath:db/migration
#    baseline-on-migrate: true
