spring:
  application:
    name: condo-swift-api
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/condo_swift_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:257890}
    
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 25MB
      
  mail:
    host: smtp.gmail.com
    port: 587
    username: jeyer44@gmail.com
    password: eiplghjkmrivnryr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

jwt-secret: 91269b51685854a2fd44cea280aa2873917b548cdb131692ae0ec534d2032c10
jwt-expiration: 604800000
  
supabase:
  url: https://syrkqqdlwkpzpwuedspt.storage.supabase.co/storage/v1
  key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5cmtxcWRsd2twenB3dWVkc3B0Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDUwNjcyMiwiZXhwIjoyMDc2MDgyNzIyfQ.XHYJHhtPVS4GGRpLJYe8Zb3WqxDR4gd-bhIYMkZiDrw
  bucket:
    announce: announce-images
    profile: profile-picture