spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    
  datasource:
    url: jdbc:postgresql://localhost:5432/condo_swift_db
    username: postgres
    password: 257890
      
    
  flyway:
    enabled: false
