spring:
  hikari:
    maximum-pool-size: 3
    minimum-idle: 1
    
  config:
    import: optional:file:.env[.properties]
  
  application:
    name: ${SPRING_APPLICATION_NAME:condo-swift-api}

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  servlet:
    multipart:
      max-file-size: ${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE:5MB}
      max-request-size: ${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE:25MB}

  jackson:
    time-zone: ${SPRING_JACKSON_TIME_ZONE:Asia/Bangkok}

user:
  timezone: ${USER_TIMEZONE:Asia/Bangkok}

# ===============================
# JWT
# ===============================
jwt-secret: ${JWT_SECRET}
jwt-expiration: ${JWT_EXPIRATION:604800000}

# ===============================
# Supabase
# ===============================
supabase:
  url: ${SUPABASE_URL}
  key: ${SUPABASE_KEY}
  bucket:
    announce: ${SUPABASE_BUCKET_ANNOUNCE:announce-images}
    profile: ${SUPABASE_BUCKET_PROFILE:profile-picture}

# ===============================
# ThaiBulk SMS
# ===============================
thaibulksms:
  key: ${THAIBULKSMS_KEY}
  secret: ${THAIBULKSMS_SECRET}
  request_url: ${THAIBULKSMS_REQUEST_URL}
  verify_url: ${THAIBULKSMS_VERIFY_URL}

# ===============================
# ThaiBulk Email
# ===============================
thaibulkemail:
  key: ${THAIBULKEMAIL_KEY}
  secret: ${THAIBULKEMAIL_SECRET}
  send_url: ${THAIBULKEMAIL_SEND_URL}
  email_sender: ${THAIBULKEMAIL_EMAIL_SENDER}

  verify_email_template_uuid: ${THAIBULKEMAIL_VERIFY_TEMPLATE_UUID}
  reset_password_template_uuid: ${THAIBULKEMAIL_RESET_PASSWORD_TEMPLATE_UUID}

  verify_production_url: ${THAIBULKEMAIL_VERIFY_PRODUCTION_URL}
  verify_dev_url: ${THAIBULKEMAIL_VERIFY_DEV_URL}
  reset_password_url: ${THAIBULKEMAIL_RESET_PASSWORD_URL}

# ===============================
# Stripe
# ===============================
stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET}
  success-url: ${STRIPE_SUCCESS_URL}
  cancel-url: ${STRIPE_CANCEL_URL}
