CREATE TABLE public.announce_agents (
                                        id bigint NOT NULL,
                                        approved_at timestamp(6) without time zone,
                                        created_at timestamp(6) without time zone,
                                        permission character varying(255),
                                        status character varying(255),
                                        agent_id bigint,
                                        announce_id bigint,
                                        approve_by bigint,
                                        CONSTRAINT announce_agents_permission_check CHECK (((permission)::text = ANY ((ARRAY['VIEW_ONLY'::character varying, 'EDIT_CONTENT'::character varying, 'FULL_ACCESS'::character varying])::text[]))),
    CONSTRAINT announce_agents_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REVOKED'::character varying])::text[])))
);


--
-- Name: announce_agents_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.announce_agents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.announce_agents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: announce_badge; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.announce_badge (
                                       id bigint NOT NULL,
                                       assigned_at timestamp(6) without time zone,
                                       expires_at timestamp(6) without time zone,
                                       announce_id bigint,
                                       badge_id bigint
);


--
-- Name: announce_badge_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.announce_badge ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.announce_badge_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: announce_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.announce_images (
                                        id bigint NOT NULL,
                                        created_at timestamp(6) without time zone,
                                        expire_date timestamp(6) without time zone,
                                        image_name character varying(255),
                                        image_url character varying(255),
                                        announce_id bigint
);


--
-- Name: announce_images_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.announce_images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.announce_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: announce_state_approve; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.announce_state_approve (
                                               id bigint NOT NULL,
                                               status_name character varying(255),
                                               CONSTRAINT announce_state_approve_status_name_check CHECK (((status_name)::text = ANY ((ARRAY['APPROVED'::character varying, 'REJECTED'::character varying, 'PENDING'::character varying, 'DRAFT'::character varying])::text[])))
);


--
-- Name: announce_state_approve_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.announce_state_approve ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.announce_state_approve_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: announce_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.announce_types (
                                       id bigint NOT NULL,
                                       type_name character varying(255)
);


--
-- Name: announce_types_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.announce_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.announce_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: announces; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.announces (
                                  id bigint NOT NULL,
                                  announcement_date timestamp(6) without time zone,
                                  approve_date timestamp(6) without time zone,
                                  area_size integer,
                                  bathroom_count integer,
                                  bedroom_count integer,
                                  has_convenience_store boolean,
                                  has_elevator boolean,
                                  has_fitness boolean,
                                  has_parking boolean,
                                  has_pool boolean,
                                  has_security boolean,
                                  location character varying(255),
                                  price double precision,
                                  remark character varying(255),
                                  title character varying(255),
                                  updated_at timestamp(6) without time zone,
                                  announce_type_id bigint,
                                  approve_id bigint NOT NULL,
                                  approve_by bigint,
                                  province_id bigint,
                                  sale_type_id bigint,
                                  updated_by bigint,
                                  user_id bigint
);


--
-- Name: announces_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.announces ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.announces_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: badges; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.badges (
                               id bigint NOT NULL,
                               badge_name character varying(255)
);


--
-- Name: badges_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.badges ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.badges_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: black_list_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.black_list_tokens (
                                          id bigint NOT NULL,
                                          expires_at timestamp(6) without time zone,
                                          token text
);


--
-- Name: black_list_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.black_list_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.black_list_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bookmarks_announce; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bookmarks_announce (
                                           user_id bigint NOT NULL,
                                           announce_id bigint NOT NULL
);


--
-- Name: credit_transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.credit_transactions (
                                            id bigint NOT NULL,
                                            created_at timestamp(6) without time zone,
                                            credit_amount integer NOT NULL,
                                            type character varying(10),
                                            order_id bigint,
                                            user_id bigint
);


--
-- Name: credit_transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.credit_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.credit_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: map_point; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.map_point (
                                  id bigint NOT NULL,
                                  created_at timestamp(6) without time zone,
                                  lat double precision,
                                  lng double precision,
                                  announce_id bigint
);


--
-- Name: map_point_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.map_point ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.map_point_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notification_recipients; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notification_recipients (
                                                id bigint NOT NULL,
                                                expired_date timestamp(6) without time zone,
                                                is_read boolean,
                                                notify_id bigint,
                                                recipient_id bigint
);


--
-- Name: notification_recipients_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notification_recipients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_recipients_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
                                      id bigint NOT NULL,
                                      created_date timestamp(6) without time zone,
                                      expired timestamp(6) without time zone,
                                      message character varying(255),
                                      title character varying(255),
                                      sender_id bigint
);


--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.orders (
                               id bigint NOT NULL,
                               amount bigint,
                               created_at timestamp(6) without time zone,
                               currency character varying(255),
                               order_no uuid NOT NULL,
                               paid_at timestamp(6) without time zone,
                               status character varying(255),
                               stripe_payment_intent character varying(255),
                               stripe_session_id character varying(255),
                               package_id bigint,
                               user_id bigint,
                               CONSTRAINT orders_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PAID'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: packages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.packages (
                                 id bigint NOT NULL,
                                 credit_amount integer NOT NULL,
                                 currency character varying(255),
                                 is_active boolean NOT NULL,
                                 name character varying(255),
                                 price numeric(10,2)
);


--
-- Name: packages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.packages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.packages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: password_reset_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.password_reset_tokens (
                                              id bigint NOT NULL,
                                              email character varying(255),
                                              expiry_date timestamp(6) without time zone,
                                              token character varying(255)
);


--
-- Name: password_reset_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.password_reset_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_reset_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: phone_verification; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.phone_verification (
                                           id bigint NOT NULL,
                                           expiry_time timestamp(6) without time zone,
                                           otp character varying(255),
                                           phone_number character varying(255),
                                           verified boolean NOT NULL,
                                           user_id bigint
);


--
-- Name: phone_verification_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.phone_verification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.phone_verification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: provinces; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.provinces (
                                  id bigint NOT NULL,
                                  name character varying(255)
);


--
-- Name: provinces_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.provinces ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.provinces_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
                              id bigint NOT NULL,
                              role_name character varying(255),
                              CONSTRAINT roles_role_name_check CHECK (((role_name)::text = ANY ((ARRAY['ADMIN'::character varying, 'MODERATOR'::character varying, 'AGENT'::character varying, 'USER'::character varying, 'OWNER'::character varying])::text[])))
);


--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sale_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sale_types (
                                   id bigint NOT NULL,
                                   type character varying(255)
);


--
-- Name: sale_types_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sale_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sale_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stations (
                                 id bigint NOT NULL,
                                 lat double precision,
                                 lng double precision,
                                 name character varying(255),
                                 station_type character varying(255)
);


--
-- Name: stations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stripe_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stripe_events (
                                      id bigint NOT NULL,
                                      created_at timestamp(6) without time zone,
                                      event_id character varying(255),
                                      type character varying(255)
);


--
-- Name: stripe_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stripe_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stripe_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: terms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.terms (
                              id bigint NOT NULL,
                              content text NOT NULL,
                              created_at timestamp(6) without time zone NOT NULL,
                              is_active boolean NOT NULL,
                              type character varying(255) NOT NULL,
                              version character varying(255) NOT NULL,
                              CONSTRAINT terms_type_check CHECK (((type)::text = ANY ((ARRAY['AGENT_CONTACT_POLICY'::character varying, 'REGISTER_TERMS'::character varying])::text[])))
);


--
-- Name: terms_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.terms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.terms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_role; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_role (
                                  user_id bigint NOT NULL,
                                  role_id bigint NOT NULL
);


--
-- Name: user_terms_accept_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_terms_accept_logs (
                                               id bigint NOT NULL,
                                               accepted_at timestamp(6) without time zone NOT NULL,
                                               ip_address character varying(255) NOT NULL,
                                               user_agent character varying(255) NOT NULL,
                                               terms_id bigint,
                                               user_id bigint
);


--
-- Name: user_terms_accept_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_terms_accept_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_terms_accept_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
                              id bigint NOT NULL,
                              line_id character varying(255),
                              created_at timestamp(6) without time zone,
                              credit_balance numeric(38,2),
                              description character varying(255),
                              email character varying(255),
                              email_verified boolean,
                              image character varying(255),
                              name character varying(255),
                              password character varying(255),
                              phone character varying(255),
                              phone_verified boolean
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: verification_otp_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.verification_otp_token (
                                               id bigint NOT NULL,
                                               expired_at timestamp(6) without time zone,
                                               refno character varying(255),
                                               token character varying(255),
                                               user_id bigint NOT NULL
);


--
-- Name: verification_otp_token_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.verification_otp_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.verification_otp_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: verification_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.verification_token (
                                           id bigint NOT NULL,
                                           expiry_date timestamp(6) without time zone,
                                           token character varying(255),
                                           user_id bigint NOT NULL
);


--
-- Name: verification_token_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.verification_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.verification_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: villas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.villas (
                               id bigint NOT NULL,
                               name character varying(255),
                               province character varying(255)
);


--
-- Name: villas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.villas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.villas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: announce_agents announce_agents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.announce_agents
    ADD CONSTRAINT announce_agents_pkey PRIMARY KEY (id);


--
-- Name: announce_badge announce_badge_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.announce_badge
    ADD CONSTRAINT announce_badge_pkey PRIMARY KEY (id);


--
-- Name: announce_images announce_images_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.announce_images
    ADD CONSTRAINT announce_images_pkey PRIMARY KEY (id);


--
-- Name: announce_state_approve announce_state_approve_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.announce_state_approve
    ADD CONSTRAINT announce_state_approve_pkey PRIMARY KEY (id);


--
-- Name: announce_types announce_types_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.announce_types
    ADD CONSTRAINT announce_types_pkey PRIMARY KEY (id);


--
-- Name: announces announces_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.announces
    ADD CONSTRAINT announces_pkey PRIMARY KEY (id);


--
-- Name: badges badges_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.badges
    ADD CONSTRAINT badges_pkey PRIMARY KEY (id);


--
-- Name: black_list_tokens black_list_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.black_list_tokens
    ADD CONSTRAINT black_list_tokens_pkey PRIMARY KEY (id);


--
-- Name: bookmarks_announce bookmarks_announce_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookmarks_announce
    ADD CONSTRAINT bookmarks_announce_pkey PRIMARY KEY (user_id, announce_id);


--
-- Name: credit_transactions credit_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credit_transactions
    ADD CONSTRAINT credit_transactions_pkey PRIMARY KEY (id);

-- Name: map_point map_point_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.map_point
    ADD CONSTRAINT map_point_pkey PRIMARY KEY (id);


--
-- Name: notification_recipients notification_recipients_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_recipients
    ADD CONSTRAINT notification_recipients_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: packages packages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.packages
    ADD CONSTRAINT packages_pkey PRIMARY KEY (id);


--
-- Name: password_reset_tokens password_reset_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);


--
-- Name: phone_verification phone_verification_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.phone_verification
    ADD CONSTRAINT phone_verification_pkey PRIMARY KEY (id);


--
-- Name: provinces provinces_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provinces
    ADD CONSTRAINT provinces_pkey PRIMARY KEY (id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: sale_types sale_types_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sale_types
    ADD CONSTRAINT sale_types_pkey PRIMARY KEY (id);


--
-- Name: stations stations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stations
    ADD CONSTRAINT stations_pkey PRIMARY KEY (id);


--
-- Name: stripe_events stripe_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stripe_events
    ADD CONSTRAINT stripe_events_pkey PRIMARY KEY (id);


--
-- Name: terms terms_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.terms
    ADD CONSTRAINT terms_pkey PRIMARY KEY (id);


--
-- Name: phone_verification uk4yuf379o70sr3avcho588ufhg; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.phone_verification
    ADD CONSTRAINT uk4yuf379o70sr3avcho588ufhg UNIQUE (user_id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: users ukdu5v5sr43g5bfnji4vb8hg5s3; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukdu5v5sr43g5bfnji4vb8hg5s3 UNIQUE (phone);


--
-- Name: orders ukg8pohnngqi5x1nask7nff2u7w; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT ukg8pohnngqi5x1nask7nff2u7w UNIQUE (order_no);


--
-- Name: stripe_events ukhog0ya1x6wooel0gtetv4xnwa; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stripe_events
    ADD CONSTRAINT ukhog0ya1x6wooel0gtetv4xnwa UNIQUE (event_id);


--
-- Name: verification_token ukq6jibbenp7o9v6tq178xg88hg; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.verification_token
    ADD CONSTRAINT ukq6jibbenp7o9v6tq178xg88hg UNIQUE (user_id);


--
-- Name: verification_otp_token ukriui2cih7ssultvjayt2xoeig; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.verification_otp_token
    ADD CONSTRAINT ukriui2cih7ssultvjayt2xoeig UNIQUE (user_id);


--
-- Name: user_role user_role_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT user_role_pkey PRIMARY KEY (user_id, role_id);


--
-- Name: user_terms_accept_logs user_terms_accept_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_terms_accept_logs
    ADD CONSTRAINT user_terms_accept_logs_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: verification_otp_token verification_otp_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.verification_otp_token
    ADD CONSTRAINT verification_otp_token_pkey PRIMARY KEY (id);


--
-- Name: verification_token verification_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.verification_token
    ADD CONSTRAINT verification_token_pkey PRIMARY KEY (id);


--
-- Name: villas villas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.villas
    ADD CONSTRAINT villas_pkey PRIMARY KEY (id);



-- Name: notifications fk13vcnq3ukas06ho1yrbc5lrb5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk13vcnq3ukas06ho1yrbc5lrb5 FOREIGN KEY (sender_id) REFERENCES public.users(id);


--
-- Name: announces fk29ephlwuqkgw3wvgahj4tpybq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.announces
    ADD CONSTRAINT fk29ephlwuqkgw3wvgahj4tpybq FOREIGN KEY (announce_type_id) REFERENCES public.announce_types(id);


--
-- Name: map_point fk2tnj991ck7h2hlnxqypjc1ked; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.map_point
    ADD CONSTRAINT fk2tnj991ck7h2hlnxqypjc1ked FOREIGN KEY (announce_id) REFERENCES public.announces(id);


--
-- Name: credit_transactions fk2w1fen9qw5j3aissw8yg1xxtx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credit_transactions
    ADD CONSTRAINT fk2w1fen9qw5j3aissw8yg1xxtx FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: announce_images fk30qdhuxfrj78c52c4syhvm546; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.announce_images
    ADD CONSTRAINT fk30qdhuxfrj78c52c4syhvm546 FOREIGN KEY (announce_id) REFERENCES public.announces(id);


--
-- Name: orders fk32ql8ubntj5uh44ph9659tiih; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk32ql8ubntj5uh44ph9659tiih FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: verification_token fk3asw9wnv76uxu3kr1ekq4i1ld; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.verification_token
    ADD CONSTRAINT fk3asw9wnv76uxu3kr1ekq4i1ld FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: announces fk3saq5ra86t8d4x461g9g2c38i; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.announces
    ADD CONSTRAINT fk3saq5ra86t8d4x461g9g2c38i FOREIGN KEY (updated_by) REFERENCES public.users(id);


--
-- Name: announces fk5bciph6umrpw5tr1t9vxmfjye; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.announces
    ADD CONSTRAINT fk5bciph6umrpw5tr1t9vxmfjye FOREIGN KEY (province_id) REFERENCES public.provinces(id);


--
-- Name: orders fk6kb9u6u1oyil56npvm02vsvoo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk6kb9u6u1oyil56npvm02vsvoo FOREIGN KEY (package_id) REFERENCES public.packages(id);


--
-- Name: announces fk8esjv8rd5eq1sexwqlqg7daqv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.announces
    ADD CONSTRAINT fk8esjv8rd5eq1sexwqlqg7daqv FOREIGN KEY (approve_by) REFERENCES public.users(id);


--
-- Name: announces fkb77y54420nuwh4fhbstxau2de; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.announces
    ADD CONSTRAINT fkb77y54420nuwh4fhbstxau2de FOREIGN KEY (approve_id) REFERENCES public.announce_state_approve(id);


--
-- Name: announces fkcjwod1ub1i5lno2cmihvvl2f6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.announces
    ADD CONSTRAINT fkcjwod1ub1i5lno2cmihvvl2f6 FOREIGN KEY (sale_type_id) REFERENCES public.sale_types(id);


--
-- Name: bookmarks_announce fkctf0a1b8v0565pvg7no99a41e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookmarks_announce
    ADD CONSTRAINT fkctf0a1b8v0565pvg7no99a41e FOREIGN KEY (announce_id) REFERENCES public.announces(id);


--
-- Name: notification_recipients fkhmk9x7vavgw3h0wpjntg0d1j1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_recipients
    ADD CONSTRAINT fkhmk9x7vavgw3h0wpjntg0d1j1 FOREIGN KEY (recipient_id) REFERENCES public.users(id);


--
-- Name: announces fkhrk61v9pg80cuogbbjiknubcb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.announces
    ADD CONSTRAINT fkhrk61v9pg80cuogbbjiknubcb FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: announce_agents fkip4via4gnnislh59k12q6ntvs; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.announce_agents
    ADD CONSTRAINT fkip4via4gnnislh59k12q6ntvs FOREIGN KEY (agent_id) REFERENCES public.users(id);


--
-- Name: user_role fkj345gk1bovqvfame88rcx7yyx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT fkj345gk1bovqvfame88rcx7yyx FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: credit_transactions fkjl0dwyeb8wag4j40g87uhvk8d; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credit_transactions
    ADD CONSTRAINT fkjl0dwyeb8wag4j40g87uhvk8d FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: bookmarks_announce fkkpxm4m1g089wy92j2s2vj37b9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookmarks_announce
    ADD CONSTRAINT fkkpxm4m1g089wy92j2s2vj37b9 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: verification_otp_token fkl1fb5n9hll8gu38u5ocf5bu8g; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.verification_otp_token
    ADD CONSTRAINT fkl1fb5n9hll8gu38u5ocf5bu8g FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: user_terms_accept_logs fkleb6dfdhvru84stshmbum13i4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_terms_accept_logs
    ADD CONSTRAINT fkleb6dfdhvru84stshmbum13i4 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: user_terms_accept_logs fklx5sm492bfic7mkcwhefhvd7u; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_terms_accept_logs
    ADD CONSTRAINT fklx5sm492bfic7mkcwhefhvd7u FOREIGN KEY (terms_id) REFERENCES public.terms(id);


--
-- Name: phone_verification fkn74ijm3jdnah67brig7wro468; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.phone_verification
    ADD CONSTRAINT fkn74ijm3jdnah67brig7wro468 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: announce_badge fknmcrfcuxp0jwyhkhxnacyqme2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.announce_badge
    ADD CONSTRAINT fknmcrfcuxp0jwyhkhxnacyqme2 FOREIGN KEY (badge_id) REFERENCES public.badges(id);


--
-- Name: announce_badge fko35hj2pqpypxwbbdk1g76eq2s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.announce_badge
    ADD CONSTRAINT fko35hj2pqpypxwbbdk1g76eq2s FOREIGN KEY (announce_id) REFERENCES public.announces(id);


--
-- Name: announce_agents fkogqorinnkhhglybxqivnnn7kw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.announce_agents
    ADD CONSTRAINT fkogqorinnkhhglybxqivnnn7kw FOREIGN KEY (approve_by) REFERENCES public.users(id);


--
-- Name: announce_agents fkr5l9ib33c6ookum5lq6hpib45; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.announce_agents
    ADD CONSTRAINT fkr5l9ib33c6ookum5lq6hpib45 FOREIGN KEY (announce_id) REFERENCES public.announces(id);


--
-- Name: notification_recipients fks38lnd0irxv33lyk1ltq7b2hk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_recipients
    ADD CONSTRAINT fks38lnd0irxv33lyk1ltq7b2hk FOREIGN KEY (notify_id) REFERENCES public.notifications(id);


--
-- Name: user_role fkt7e7djp752sqn6w22i6ocqy6q; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT fkt7e7djp752sqn6w22i6ocqy6q FOREIGN KEY (role_id) REFERENCES public.roles(id);